kind: Service
apiVersion: v1
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
      tier: backend
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        tier: backend
    spec:
      containers:
      - name: ${SERVICE_NAME}
        image: gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
        env:
        - name: DB_HOST
          value: "35.184.198.183"
        - name: DB_PORT
          value: 5432
        - name: DB_NAME
          value: "postgres" 
        - name: DB_USER
          value: "postgres"    
        - name: DB_PASS
          value: "YnSdt8CughGp"      
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP